name: Python Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-dev \
          build-essential \
          libssl-dev \
          libffi-dev \
          libxml2-dev \
          libxslt1-dev \
          libjpeg-dev \
          zlib1g-dev \
          libpng-dev \
          curl
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install lxml>=4.9.3 lxml-html-clean>=1.0.0
        pip install -r requirements.txt
        python -m nltk.downloader punkt
    
    - name: Create .env file
      run: |
        echo "FLASK_ENV=testing" >> .env
        echo "SECRET_KEY=dummy-key-for-testing" >> .env
        echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" >> .env
    
    - name: Test app initialization
      run: |
        python -c "from app import create_app; app = create_app()" 